name: View Secrets

on:
  workflow_dispatch:

jobs:
  view-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Print some environment variables
        run: |
          echo "Secret Value is stored but not displayed for security reasons."
          echo "You can use the Secret in your code."
          echo "My Secret: ${{ EnvSec.test }} - ${{ secrets.EnvSec }} - ${{ secrets.test }}"
