name: Example Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - pro

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Build
        run: |
          echo "Selected environment: ${{ github.event.inputs.environment }}"
          if [ "${{ github.event.inputs.environment }}" == "pro" ]; then
            echo "Building for production..."
          else
            echo "Building for development..."
          fi
